# @changed 2024.08.04, 22:05
# @see https://eslint.org/docs/rules/

'$schema': https://json.schemastore.org/eslintrc
root: true
extends:
  - next/core-web-vitals
  - prettier
  - plugin:tailwindcss/recommended
  # - 'next/core-web-vitals'
  # - 'eslint:recommended'
  # - 'plugin:jest/recommended'
plugins:
  - tailwindcss
rules:
  # "@next/next/no-html-link-for-pages": off
  react/jsx-key: off
  tailwindcss/no-custom-classname: off
  tailwindcss/classnames-order: warn
  # XXX
  # curly: warn
  no-console: warn
  no-debugger: warn
  no-extra-semi: warn
  no-redeclare: warn
  no-undef: error
  no-unreachable: warn
  prefer-const: warn
  no-empty: warn
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
settings:
  tailwindcss:
    callees:
      - cn
    config: tailwind.config.ts
  next:
    rootDir: true

env:
  es6: true
  # jest: true
  # jest/globals: true
  # amd: true
  commonjs: true

overrides:
  - # Typescript files (ts,tsx)...
    files: '**/*.+(ts|tsx)'
    parser: '@typescript-eslint/parser'
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended' # prettier: Slighly slower (+0.3s)
      - 'plugin:react/recommended'
      - 'plugin:react/jsx-runtime'
      # - 'plugin:react-hooks/recommended'
      - 'plugin:@typescript-eslint/recommended'
      # - 'plugin:@next/next/recommended'
    settings:
      react:
        version: 'detect'
    parserOptions:
      ecmaVersion: 12
      sourceType: 'module'
      # project: './tsconfig.json' # Very slow
    plugins:
      # - 'react'
      - '@typescript-eslint'
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      curly:
        - 'warn'
        - 'all'
      # curly: warn
      no-undef: off # Disable js no-undef rule for typescript sources. Using ts2304 instead.
      # eslint-comments/no-use: warn
      no-debugger: warn
      no-console: warn # TODO: To use if console debugging output is deprecated (44 warnings as on 2022.04.06).
      prettier/prettier: # prettier: Slighly slower (+0.3s)
        - 'warn' # Can we to use warn if we still use `eslint --max-warnings=0` in `package.json`?
        - endOfLine: 'auto'
      import/no-namespace: off
      no-unused-vars: off
      prefer-const: warn
      '@typescript-eslint/explicit-member-accessibility':
        - 'error'
        - accessibility: 'no-public'
      '@typescript-eslint/no-unused-vars':
        - 'warn'
        - # varsIgnorePattern: '^[T][A-Z]\\w+' # M.b. useful for typescript `TSmth` types: eslint may treat them us 'unused'.
          varsIgnorePattern: '^_'
          argsIgnorePattern: '^_'
      '@typescript-eslint/no-require-imports': warn
      '@typescript-eslint/array-type': error
      '@typescript-eslint/ban-ts-comment': off
      # NOTE 2024.09.08, 23:11 -- Disabled because of several 'ts-nocheck'
      # '@typescript-eslint/ban-ts-comment':
      #   - 'error'
      #   - ts-ignore: 'allow-with-description'
      # NOTE 2024.09.08, 23:11 -- It's false-positive for typescript's 'in', like: `export type ChartConfig = { [k in string]: ... }`
      # '@typescript-eslint/naming-convention':
      #   - 'error'
      #   - selector: 'function'
      #     format:
      #       - 'PascalCase'
      #       - 'camelCase'
      '@typescript-eslint/explicit-module-boundary-types': off # Disable 'Missing return type on function' if no explicit `: void` specified
      '@typescript-eslint/explicit-function-return-type': 0 # Causes 'Missing return type on function' if no explicit `: void` specified
      'func-call-spacing':
        - 'error'
        - 'never'
      '@typescript-eslint/no-explicit-any': warn
      '@typescript-eslint/no-extraneous-class':
        - 'error'
        - allowStaticOnly: true
      '@typescript-eslint/no-non-null-assertion': warn
      '@typescript-eslint/no-useless-constructor': error
      '@typescript-eslint/prefer-for-of': warn
      '@typescript-eslint/prefer-function-type': warn
      # NOTE 2024.09.08, 23:49 -- Disabled due to multiple 'An interface declaring no members...'
      '@typescript-eslint/no-empty-object-type': off
      # NOTE 2024.09.08, 23:49 -- Disabled due to multiple 'Use an `interface` instead of a `type`'
      # '@typescript-eslint/consistent-type-definitions': error
      # 'type-annotation-spacing': error # ???
      react/no-unescaped-entities: off
      react/prop-types: off
      react/no-multi-comp:
        - 'error'
        - ignoreStateless: true
      react/no-this-in-sfc: error
      react/no-unstable-nested-components: off
      react/style-prop-object: error
      react/jsx-handler-names: error
      # react/jsx-no-bind: error
      react/jsx-no-constructed-context-values: warn
      # NOTE 2024.09.08, 23:49 -- Disabled due to multiplee warnings for 'Icons.xxx'
      # react/jsx-pascal-case: error
      react/boolean-prop-naming: error
      # react/function-component-definition:
      #   - 'error'
      #   - namedComponents: 'arrow-function'
      react/jsx-uses-react: off
      react/react-in-jsx-scope: off
      react/no-array-index-key: warn
      react/jsx-boolean-value: warn
      react/jsx-fragments: error
      react/destructuring-assignment: warn
      react/sort-comp:
        - 'error'
        - order:
            - 'static-variables'
            - 'static-methods'
            - 'lifecycle'
            - 'everything-else'
            - 'rendering'
          groups:
            rendering:
              - '/^render.+$/'
              - 'render'
      # react/sort-prop-types: warn
      react/jsx-closing-tag-location: warn
      react/jsx-curly-newline: off
      react/jsx-curly-spacing: error
      react/jsx-equals-spacing: error
      react/jsx-indent:
        - 'warn'
        - 2
        - indentLogicalExpressions: false
      react/jsx-indent-props:
        - 'warn'
        - indentMode: 2
          ignoreTernaryOperator: false
      react/no-unknown-property:
        - 'error'
        - ignore:
            - 'tw'
            - 'stroke-width'
            - 'stroke-linecap'
            - 'stroke-linejoin'

  - # Raw js files (from root)...
    files: '**/*.js'
    env:
      node: true
      commonjs: true
      es6: true
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended'
      # - 'plugin:import/recommended'
    plugins:
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    # globals:
    #   require: true
    #   process: true
    rules:
      prettier/prettier: warn
      no-unused-vars:
        - 'warn'
        - argsIgnorePattern: '^_'
      no-console: warn
      no-debugger: warn
      no-extra-semi: warn
      no-redeclare: warn
      no-undef: error
      no-unreachable: warn
      prefer-const: warn
      semi:
        - 'warn'
        - 'always'

  - # Raw mjs files (from root)...
    files: '**/*.mjs'
    parserOptions:
      sourceType: 'module'
    env:
      node: true
      es6: true
    extends:
      - 'eslint:recommended'
      - 'plugin:prettier/recommended'
      # - 'plugin:import/recommended'
    plugins:
      - 'prettier' # prettier: Slighly slower (+~0.3s)
    rules:
      prettier/prettier: warn
      no-unused-vars:
        - 'warn'
        - argsIgnorePattern: '^_'
      no-console: warn
      no-debugger: warn
      no-extra-semi: warn
      no-redeclare: warn
      no-undef: error
      no-unreachable: warn
      prefer-const: warn
      semi:
        - 'warn'
        - 'always'

  # - # Raw js project files...
  #   files: '**/*.js'
  #   parser: null
  #   env:
  #     es6: true
  #     browser: true
  #   globals:
  #     modules: true
  #   extends:
  #     - 'eslint:recommended'
  #     - 'plugin:prettier/recommended'
  #   plugins:
  #     - 'prettier' # prettier: Slighly slower (+~0.3s)
  #   rules:
  #     no-var: warn
  #     prettier/prettier: warn
  #     no-unused-vars:
  #       - 'warn'
  #       - argsIgnorePattern: '^_'
  #     no-console: warn
  #     no-debugger: warn
  #     no-extra-semi: warn
  #     no-redeclare: warn
  #     no-undef: error
  #     no-unreachable: warn
  #     prefer-const: warn
  #     semi:
  #       - 'warn'
  #       - 'always'

  - # json files (@see https://www.npmjs.com/package/eslint-plugin-json)...
    files: '**/*.json'
    extends:
      # - 'plugin:json/recommended'
      - 'plugin:json/recommended-legacy'
    rules:
      prettier/prettier: warn

  - # jsonc files - commented json (@see https://www.npmjs.com/package/eslint-plugin-jsonc)...
    files: '**/*.jsonc'
    extends:
      - 'plugin:jsonc/recommended-with-jsonc'
    rules:
      prettier/prettier: warn

  - # yaml files - commented json (@see https://www.npmjs.com/package/eslint-plugin-yaml)...
    files: '**/*.+(yml|yaml)'
    plugins:
      - 'yaml'
    extends:
      - 'plugin:yaml/legacy'
