trailingComma: 'all'
printWidth: 100
tabWidth: 2
semi: true
singleQuote: true
# plugins:
#   - prettier-plugin-jinja-template
# overrides:
#   - files:
#       - '*.njk'
#     options:
#       parser: jinja-template
